// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk6rk3lEKNVc095KwBWLuvKnllENCV7qM',
    appId: '1:281358456546:web:ce8baff0d1966d1cd8f0bb',
    messagingSenderId: '281358456546',
    projectId: 'winterarcdemo',
    authDomain: 'winterarcdemo.firebaseapp.com',
    storageBucket: 'winterarcdemo.appspot.com',
    measurementId: 'G-YE55ZXCC0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS450r8sb0I4pHQFAm7TZAP5vibC4pzpM',
    appId: '1:281358456546:android:9267e2c8c90cf25ad8f0bb',
    messagingSenderId: '281358456546',
    projectId: 'winterarcdemo',
    storageBucket: 'winterarcdemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkmSUZGAUTgMlI6d_1M1jxRHCz9bH1j5o',
    appId: '1:281358456546:ios:1584bfb525a8d665d8f0bb',
    messagingSenderId: '281358456546',
    projectId: 'winterarcdemo',
    storageBucket: 'winterarcdemo.appspot.com',
    iosBundleId: 'com.example.winterArc',
  );
}
